[package]
name = "quiet"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[[bin]]
name = "quiet"
test = false
bench = false

[dependencies]
